In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 787.7 kB/s eta 0:00:20
   ---------------------------------------- 0.1/15.8 MB 901.1 kB/s eta 0:00:18
   ---------------------------------------- 0.2/15.8 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.2/15.8 MB 958.4 kB/s eta 0:00:17
    --------------------------------------- 0.2/15.8 MB 885.4 kB/s eta 0:00:18
    --------------------------------------- 0.3/15.8 MB 1.1 MB/s eta 0:00:15
   - -------------------------------------- 0.4/15.8 MB 1.2 MB/s eta 0:00:13
 

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
arr=  np.random.randint(1, 50, size=(10))

In [4]:
arr

array([21,  8,  2, 25, 10, 29, 13, 17,  5, 18])

In [6]:
np.mean(arr)

14.8

In [9]:
arr1=np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
arr2=np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [11]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [10, 12, 14]])

In [13]:
x=arr1+arr2
np.mean(x)

8.666666666666666

In [15]:
arr=  np.random.randint(1, 100, size=(20))

In [16]:
arr

array([55, 69, 31, 23, 17, 73, 68, 28, 90, 97,  2, 85, 42, 82, 14, 75, 46,
       96, 12, 72])

In [19]:
x = arr > 50
filtered_arr = arr[x]
filtered_arr

array([55, 69, 73, 68, 90, 97, 85, 82, 75, 96, 72])

In [20]:
arr1=np.array([5, 6, 7,2,3,4,5,6,8,7])

In [21]:
arr1

array([5, 6, 7, 2, 3, 4, 5, 6, 8, 7])

In [24]:
np.random.shuffle(arr1)

In [25]:
arr1

array([5, 6, 6, 7, 7, 2, 8, 3, 5, 4])

In [26]:
x = arr > 5
filtered_arr = arr[x]
filtered_arr

array([55, 69, 31, 23, 17, 73, 68, 28, 90, 97, 85, 42, 82, 14, 75, 46, 96,
       12, 72])

In [38]:
x=np.random.randint(1,10)
filtered_arr = arr1[x]
filtered_arr

4